log:
  level: DEBUG

service:
  port: 8080

db:
  sql:
    db: template7
    host: 127.0.0.1
    port: 3306
    username: admin
    password: password
    connection:
      min: 4
      max: 8
  nosql:
    db: template7
    host: 127.0.0.1
    port: 27017
    username:
    password:

redis:
  host: "localhost:6379"
  password: