env: dev

logger:
  level: debug

service:
  port: 8080

db:
  sql:
    db: template7
    host: 127.0.0.1
    port: 33306
    username: admin
    password: password
    connection:
      min: 4
      max: 8
  nosql:
    db: template7
    host: 127.0.0.1
    port: 37017
    username:
    password:

cache:
  host: "localhost:6379"
  password:

auth:
  rbacModelPath: "./config/rbac_model.conf"