// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Template7/backend/internal/auth"
	"github.com/Template7/backend/internal/cache"
	"github.com/Template7/backend/internal/config"
	"github.com/Template7/backend/internal/db"
	"github.com/Template7/backend/internal/route/handler"
	"github.com/Template7/backend/internal/route/middleWare"
	"github.com/Template7/backend/internal/user"
	"github.com/Template7/backend/internal/wallet"
	db2 "github.com/Template7/common/db"
	"github.com/Template7/common/logger"
)

import (
	_ "github.com/Template7/backend/docs"
)

// Injectors from wire.go:

func InitializeApp() *App {
	loggerLogger := logger.New()
	client := db.New(loggerLogger)
	gormDB := db2.NewSql()
	cacheInterface := cache.New(loggerLogger)
	configConfig := config.New()
	authAuth := auth.New(client, gormDB, cacheInterface, loggerLogger, configConfig)
	authController := handler.NewAuthController(authAuth, loggerLogger)
	service := user.New(authAuth, client, loggerLogger)
	userController := handler.NewUserController(service, authAuth, loggerLogger)
	walletService := wallet.New(client, loggerLogger)
	walletController := handler.NewWalletController(walletService, loggerLogger)
	controller := middleware.New(service, authAuth, loggerLogger)
	app := NewApp(authController, userController, walletController, controller, configConfig, loggerLogger)
	return app
}
