log:
  level: DEBUG

gin:
  listenPort: 8080
  mode: debug
  shutdownTimeout: 10


facebook:
  appId: "549471872922082"
  secret: "a1f5a58227a230fd3a954a19017459de"
  callback: "http://localhost:8080/api/v1/sign-in/facebook/callback"

mongo:
  db: template7
  host: 127.0.0.1
  port: 27017
  username:
  password:

redis:
  host: "localhost:6379"
  password: