log:
  level: DEBUG

gin:
  listenPort: 8080
  mode: debug
  shutdownTimeout: 10


facebook:
  app_id: 2882438808668187
  secret: 4db88a2aeafa61d01582470a76fb8025

mongo:
  db: rentdate
  host: 127.0.0.1
  port: 27017
  username:
  password:

redis:
  host: "localhost:6379"
  password: