log:
  level: DEBUG

gin:
  listenPort: 8080
  mode: debug
  shutdownTimeout: 10


facebook:
  appId:
  secret:

mongo:
  db: template7
  host: 127.0.0.1
  port: 27017
  username:
  password:

redis:
  host: "localhost:6379"
  password: