definitions:
  github_com_Template7_backend_internal_t7Error.Code:
    enum:
    - 1024
    - 1025
    - 1026
    - 1027
    - 1028
    - 1029
    - 1030
    - 1031
    - 1032
    - 1033
    - 1034
    - 1035
    - 1036
    - 1037
    - 1038
    - 1039
    - 1040
    - 1041
    - 1042
    - 1043
    - 1044
    - 1045
    type: integer
    x-enum-varnames:
    - codeUnAuthorized
    - codeInvalidBody
    - codeDbConnectionFail
    - codeDbOperationFail
    - codeInvalidDocumentId
    - codeHttpOperationFail
    - codeHttpUnexpectedResponseCode
    - codeHashFail
    - codeUserNotfound
    - codeUserAlreadyExist
    - codeSignInFail
    - codeVerifyCodeExpired
    - codeIncorrectVerifyCode
    - codeRedisOperationFail
    - codeTokenSignFail
    - codeTokenAssertionFail
    - codeInvalidToken
    - codeDecodeFail
    - codeWalletNotFound
    - codePasswordIncorrect
    - codeUserHasNoRole
    - codeUnknown
  github_com_Template7_backend_internal_t7Error.Error:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/github_com_Template7_backend_internal_t7Error.Code'
        example: 1024
      detail:
        example: empty token
        type: string
      message:
        example: token unauthorized
        type: string
      type:
        allOf:
        - $ref: '#/definitions/github_com_Template7_backend_internal_t7Error.Type'
        example: 32
    type: object
  github_com_Template7_backend_internal_t7Error.Type:
    enum:
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    type: integer
    x-enum-varnames:
    - typeAuth
    - typeInvalidData
    - typeDb
    - typeRedis
    - typeNetwork
    - typeOther
  internal_route_handler.hello:
    properties:
      message:
        example: Hello
        type: string
      timestamp:
        example: "2021-07-24T20:01:25.874565+08:00"
        type: string
    type: object
  v1.LoginRequest:
    properties:
      password:
        description: password
        type: string
      username:
        description: username
        type: string
    type: object
  v1.LoginResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: API Documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Backend API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_route_handler.hello'
      summary: Hello Page
      tags:
      - Hello
  /api/v1/login/native:
    post:
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/v1.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Template7_backend_internal_t7Error.Error'
      summary: Native login
      tags:
      - v1
      - login
swagger: "2.0"
