name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get short commit hash
        id: short_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: build/Dockerfile
          push: true
          tags: allensyk/template7-backend:latest
          build-args: |
            COMMIT_HASH=${{ env.COMMIT_HASH }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # for arm
      - name: Build and push arm64
        id: docker_build_arm64
        uses: docker/build-push-action@v5
        with:
          file: build/Dockerfile
          push: true
          platforms: linux/arm64
          tags: allensyk/template7-backend:arm64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
