name: release

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          push: true
          tags: allensyk/template7-backend:${{ steps.get_version.outputs.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # for arm
      - name: Build and push arm64
        id: docker_build_arm64
        uses: docker/build-push-action@v2
        with:
          file: build/DockerfileArm64
          push: true
          platforms: linux/arm64
          tags: allensyk/template7-backend:arm64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
